<?php

use App\Http\Controllers\UserController;
use App\Http\Controllers\GradesController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\EnrollmentController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

// Comment: This is a comment for the default route generated by Laravel, which is currently commented out.
/*Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});*/

// Comment: This route is for getting all users' data.
Route::get('/user_index', [UserController::class, 'Index']);

// Comment: This route is for authenticating a user by email and password.
Route::get('/auth/{mail}/{password}', [UserController::class, 'Find_User']);

// Comment: This route is for getting a student's data by ID.
Route::get('/data/{id}', [StudentController::class, 'getData']);

// Comment: This route is for getting a student's profile image by ID.
Route::get('/image/{id}', [StudentController::class, 'image']);

// Comment: This route is for getting all grades of a student by ID.
Route::get('/grades/{id}', [GradesController::class, 'All_Grades']);

// Comment: This route is for getting all grades of a student for a certain level by ID and level.
Route::get('/grades/{id}/{level}', [GradesController::class, 'gradesLevel']);

// Comment: This route is for getting the subject data (code, name, credit hour, state) for a student's enrollment in a certain term, identified by ID, level, and term.
Route::get('/subject/{id}/{level}/{term}', [EnrollmentController::class, 'termState']);


//Insert Enrolment
Route::post('/request/{id}/{subject}', [EnrollmentController::class, 'Request']);
