<?php

use App\Http\Controllers\UserController;
use App\Http\Controllers\GradesController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\EnrollmentController;
use App\Http\Controllers\AdvisorController;
use App\Http\Controllers\SubjectController;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

// Comment: This is a comment for the default route generated by Laravel, which is currently commented out.
/*Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});*/


//-------User----------------------------
//----------------------------------------
// Comment: This route is for getting all users' data.
Route::get('/user_index', [UserController::class, 'Index']);

// Comment: This route is for authenticating a user by email and password.
Route::get('/auth/{mail}/{password}', [UserController::class, 'Find_User']);




//-------Student--------------------------
//----------------------------------------

// Comment: This route is for getting a student's profile image by ID.
Route::get('/studentImage/{id}', [StudentController::class, 'getImage']);

// Comment: This route is for getting all grades of a student by ID.
Route::get('/grades/{id}', [GradesController::class, 'All_Grades']);

// Comment: This route is for getting all grades of a student for a certain level by ID and level.
Route::get('/grades/{id}/{level}', [GradesController::class, 'gradesLevel']);

// Comment: This route is for getting the subject data (code, name, credit hour, state) for a student's enrollment in a certain term, identified by ID, level, and term.
Route::get('/STUsubject/{id}', [EnrollmentController::class, 'termState']);

//Insert Enrolment
Route::post('/request/{id}/{subject}', [EnrollmentController::class, 'Request']);




//-------Advisor--------------------------
//----------------------------------------
Route::get('/advisorImage/{id}', [AdvisorController::class, 'getImage']);

// insert grades or update
Route::put('/enrolment/insertGrades/{studentId}/{subjectId}/{grade}/{score}', [EnrollmentController::class, 'setGrade']);




//-------------Subject-------------------
//get all subject status(open or closed)
Route::get('/ADDsubject/subjectStatus', [SubjectController::class, 'getStatus']);

//post request to change subject state (open or closed) for advisor
Route::put('/subject/update/{subjectId}/{subjectStatus}', [SubjectController::class, 'setStatus']);
